#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: c2a5a651-f8a8-4338-bb95-ed78fa17220c
# Source File: AccountRenamer.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
6BkAAB+LCAAAAAAABADVmWtv2jAUhr9P2n+I8hkBuXGRIFLL2mla11XAun2rnHCgXoONHAfIfv0c
Eu65mLSwTpUqEuy8PufxGx+bTh9cOgcWfkIcKeKDjynpqrpqf/ygKJ3vDE8wQd4t9uAeTcG+cl0a
EN4HIq5YdeaPO7WjRnFX5ze4XOHhDLrqIPQ5TKs/MRnRhV+9pWwa/68oaV9VlMdkJGa1Hv1VlF7g
8YBBl0DAGfIqykPgeNj9CuGQvgDpOs0mslyrobUNE+qttqpEI+yqY/E8TVXcZ+yNmGin9ijhjHp+
HKEY6AOjM2A8TDr0PAyED/AfUG3T0iuKabU6tXWjjE5R2Kq90ipsO4QlV+0ozuOmN3OhnbS7o2iU
PPMp+typrb5dNy3O72dGg9k1XZ49x5NIyKFLIy/Px4m4oy7iYgCqrYk0N5tH6cjK80ZPokcM0jCF
gmZYEh2GyPlCRrAU9OVaDzidCZ7I80Gmw4r+PSyULyRiu8pAWr93yNfM55tL2LIEgHZKoEWQ0yhk
YdZaWkWx5FS2nNOmUQnSeazvkM+VKK70fsWso0ddAjWBRTTWFYIC2Hm4mxVF11NjzcK9IyzZL0He
aAmtumSfQui1GMXWhkc33qEv9fK+bJR0ZTrcDERmvYQr5RRe5cofPrD/xZX/xJGnu1E3S7kxA3aB
Gw8vi4FdB5xTcnZezkpGIBpjNj2tKLohyPFgJF9Q7KyxLfEqNHX5OmpvmNK1VFOs5LpM6ZX/sk23
pfxghHkfsR8gb8BDD66R+9KjHmWqPWTBcd5Onyp97D5fyt804LOAx09/TQ2tp1ovHf6upjR7Mbsi
fx9vcvLoy4wppr/1+avxXdTp8Xa4LDmjIapWTTveZeb7NhaVt207YxF+C3DSYznNtQc7YrE1d1/2
w39a3TvYGp88WS5eseWeSOS6vCHUtbTlMr9ek3FssoQb5nkmSrmdci9gLJoBebXaO6rUAjFMmVIt
v1BLL6DSCa8VTynItew9Uzbk1CmUU5DtXxQjumGMMqEwxyNgZwcFkdosUdMyDwMFOoQJsIThjkX7
MAaB14X9g8baJhV7ydpPxpXvw1QME/x16+ROaCdhf0METWAqZn71KuA0Pibahm/Ihm9ozthoWQ00
MhomRAdgG6VD5anvUuZh5w2SnKMSx3cJjTefOsWK0SH6ZYQYWmAyKaNVN8bWuDnWtJFVRwYq1vo1
9S4TE2bCIJSFA2Bz7EIpZCdH16MMLhJeEpV4K4jQzhDb5jJ+q3Rqu7/s2H8BUk5tq+gZAAA=#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2014 v4.1.58
     Generated on:       6/26/2014 2:10 PM
     Generated by:       dpollay
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2014
#>
#----------------------------------------------
#region Application Functions
#----------------------------------------------

function OnApplicationLoad {
	#Note: This function is not called in Projects
	#Note: This function runs before the form is created
	#Note: To get the script directory in the Packager use: Split-Path $hostinvocation.MyCommand.path
	#Note: To get the console output in the Packager (Windows Mode) use: $ConsoleOutput (Type: System.Collections.ArrayList)
	#Important: Form controls cannot be accessed in this function
	#TODO: Add modules and custom code to validate the application load
	Import-Module ShowUI
	Import-Module ActiveDirectory
	
	return $true #return true for success or false for failure
}

function OnApplicationExit {
	#Note: This function is not called in Projects
	#Note: This function runs after the form is closed
	#TODO: Add custom code to clean up and unload modules when the application exits
	
	$script:ExitCode = 0 #Set the exit code for the Packager
}

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Call-AccountRenamer_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$form1 = New-Object 'System.Windows.Forms.Form'
	$groupbox3 = New-Object 'System.Windows.Forms.GroupBox'
	$groupbox4 = New-Object 'System.Windows.Forms.GroupBox'
	$newLastName = New-Object 'System.Windows.Forms.TextBox'
	$groupbox2 = New-Object 'System.Windows.Forms.GroupBox'
	$newName = New-Object 'System.Windows.Forms.TextBox'
	$buttonConfirm = New-Object 'System.Windows.Forms.Button'
	$outputWindow = New-Object 'System.Windows.Forms.RichTextBox'
	$buttonRename = New-Object 'System.Windows.Forms.Button'
	$groupbox1 = New-Object 'System.Windows.Forms.GroupBox'
	$userName = New-Object 'System.Windows.Forms.TextBox'
	$errorprovider1 = New-Object 'System.Windows.Forms.ErrorProvider'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	
	
	
	
	
	$form1_Load={
		
	}
	
	$buttonRename_Click = {
		if ($newName.Text -eq $null -or $newName.Text -eq "")
		{
			$outputWindow.Text = "Please enter a new User Name"
			exit
		}
		elseif ($userName.Text -eq $null -or $userName.Text -eq "")
		{
			$outputWindow.Text = "Please enter a User Name"
			exit
		}
		else
		{
			$AccountInfo = Get-ADUser $userName.Text -Properties *
			$outputWindow.Text = "*** The following changes will be made in AD ***`r`n`r`n"
			$outputWindow.Text += "User Name:  " + $AccountInfo.SamAccountName + " to " + $newName.Text + "`r`n"
			$outputWindow.Text += "Last Name:  " + $AccountInfo.Surname + " to " + $newLastName.Text + "`r`n"
			$outputWindow.Text += "Display Name:  " + $AccountInfo.DisplayName + " to " + $AccountInfo.GivenName + " " + $newLastName.Text + "`r`n"
			$outputWindow.Text += "Mail:  " + $AccountInfo.Mail + " to " + $newName.Text + "@nycourts.gov`r`n"
			$outputWindow.Text += "mailNickname:  " + $AccountInfo.mailNickname + " to " + $newName.Text + "`r`n"
			foreach ($address in $AccountInfo.proxyAddresses)
			{
				if ($address -clike "SMTP:*")
				{
					$address2 = $address -creplace "SMTP:", "smtp:"
					$outputWindow.Text += "proxyAddress:  " + $address + " to " + $address2 + "`r`n"
				}
			}
			$outputWindow.Text += "Default proxyAddress:  SMTP:" + $newName.Text + "@nycourts.gov`r`n`r`n"
			$outputWindow.Text += "*** If all of the above changes look good click the Confirm Button below ***"
		}
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$form1.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonRename.remove_Click($buttonRename_Click)
			$form1.remove_Load($form1_Load)
			$form1.remove_Load($Form_StateCorrection_Load)
			$form1.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$form1.SuspendLayout()
	$groupbox3.SuspendLayout()
	$groupbox4.SuspendLayout()
	$groupbox2.SuspendLayout()
	$groupbox1.SuspendLayout()
	#
	# form1
	#
	$form1.Controls.Add($groupbox3)
	$form1.Controls.Add($buttonConfirm)
	$form1.Controls.Add($outputWindow)
	$form1.Controls.Add($buttonRename)
	$form1.Controls.Add($groupbox1)
	$form1.ClientSize = '452, 458'
	$form1.Name = "form1"
	$form1.Text = "Form"
	$form1.add_Load($form1_Load)
	#
	# groupbox3
	#
	$groupbox3.Controls.Add($groupbox4)
	$groupbox3.Controls.Add($groupbox2)
	$groupbox3.Location = '12, 77'
	$groupbox3.Name = "groupbox3"
	$groupbox3.Size = '342, 135'
	$groupbox3.TabIndex = 4
	$groupbox3.TabStop = $False
	$groupbox3.Text = "New Information"
	#
	# groupbox4
	#
	$groupbox4.Controls.Add($newLastName)
	$groupbox4.Location = '155, 19'
	$groupbox4.Name = "groupbox4"
	$groupbox4.Size = '181, 59'
	$groupbox4.TabIndex = 3
	$groupbox4.TabStop = $False
	$groupbox4.Text = "New Last Name"
	#
	# newLastName
	#
	$newLastName.Location = '7, 22'
	$newLastName.Name = "newLastName"
	$newLastName.Size = '168, 20'
	$newLastName.TabIndex = 3
	#
	# groupbox2
	#
	$groupbox2.Controls.Add($newName)
	$groupbox2.Location = '6, 19'
	$groupbox2.Name = "groupbox2"
	$groupbox2.Size = '140, 59'
	$groupbox2.TabIndex = 2
	$groupbox2.TabStop = $False
	$groupbox2.Text = "New User Name"
	#
	# newName
	#
	$newName.Location = '7, 22'
	$newName.Name = "newName"
	$newName.Size = '124, 20'
	$newName.TabIndex = 2
	#
	# buttonConfirm
	#
	$buttonConfirm.Enabled = $False
	$buttonConfirm.Location = '188, 427'
	$buttonConfirm.Name = "buttonConfirm"
	$buttonConfirm.Size = '75, 23'
	$buttonConfirm.TabIndex = 3
	$buttonConfirm.Text = "Confirm"
	$buttonConfirm.UseVisualStyleBackColor = $True
	#
	# outputWindow
	#
	$outputWindow.Location = '12, 220'
	$outputWindow.Name = "outputWindow"
	$outputWindow.Size = '427, 201'
	$outputWindow.TabIndex = 0
	$outputWindow.Text = ""
	#
	# buttonRename
	#
	$buttonRename.Location = '361, 118'
	$buttonRename.Name = "buttonRename"
	$buttonRename.Size = '79, 59'
	$buttonRename.TabIndex = 0
	$buttonRename.Text = "Rename"
	$buttonRename.UseVisualStyleBackColor = $True
	$buttonRename.add_Click($buttonRename_Click)
	#
	# groupbox1
	#
	$groupbox1.Controls.Add($userName)
	$groupbox1.Location = '160, 12'
	$groupbox1.Name = "groupbox1"
	$groupbox1.Size = '134, 59'
	$groupbox1.TabIndex = 0
	$groupbox1.TabStop = $False
	$groupbox1.Text = "Current User Name"
	#
	# userName
	#
	$userName.Location = '7, 20'
	$userName.Name = "userName"
	$userName.Size = '118, 20'
	$userName.TabIndex = 1
	#
	# errorprovider1
	#
	$errorprovider1.ContainerControl = $form1
	$groupbox1.ResumeLayout($false)
	$groupbox2.ResumeLayout($false)
	$groupbox4.ResumeLayout($false)
	$groupbox3.ResumeLayout($false)
	$form1.ResumeLayout($false)
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $form1.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$form1.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$form1.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $form1.ShowDialog()

} #End Function

#Call OnApplicationLoad to initialize
if((OnApplicationLoad) -eq $true)
{
	#Call the form
	Call-AccountRenamer_psf | Out-Null
	#Perform cleanup
	OnApplicationExit
}
